<a href="https://colab.research.google.com/github/Rathachai/CV/blob/gh-pages/code/ch03/numpy-pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analytics Book : CODE

**ISBN** : 978-616-338-169-9

**Author** : Rathachai Chawuthai

**Year** : 2022

**Copyright** © by KMITL

**Link** : https://github.com/Rathachai/DA-LAB



---



## **Chapter 3 : Data Processing**


---


### Numpy

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a = np.array([1,2,3])

In [4]:
b = np.array([10,20,30])

In [5]:
a+b

array([11, 22, 33])

In [6]:
a*3

array([3, 6, 9])

In [7]:
my_array = np.array([1,2,3,4])

In [8]:
np.sqrt(my_array)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [9]:
np.sum(my_array)

10



---



## **Pandas**

In [10]:
import pandas as pd

In [11]:
CSV_PATH = "https://rathachai.github.io/DA-LAB/datasets/simple-employee-db.csv"

In [12]:
df = pd.read_csv(CSV_PATH)

In [13]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [14]:
df["name"]

0        Anda
1      Bordin
2    Chantana
3     Donlaya
4     Ekkasit
5      Fundee
6     Gitiwit
7       Harit
Name: name, dtype: object

In [15]:
df[["name", "gender", "age"]]

name  gender  age
0      Anda  female   39
1    Bordin    male   25
2  Chantana  female   29
3   Donlaya  female   39
4   Ekkasit    male   37
5    Fundee  female   35
6   Gitiwit    male   26
7     Harit    male   32

In [16]:
df.loc[1]

eid                   E012
name                Bordin
gender                male
department       developer
age                     25
salary             48700.0
working_years            2
birth_place         Phuket
Name: 1, dtype: object

In [17]:
df.loc[[1,2,3]]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

In [18]:
df[["name", "age"]].loc[[1,2,3]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [19]:
df.loc[[1,2,3]][["name", "age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [20]:
df[ (df["working_years"]>3) & (df["salary"]>70000) ]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [21]:
df.loc[0,"working_years"] = 77

In [22]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0             77     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [23]:
df.set_index("eid", inplace=True)

In [24]:
df

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0             77     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

In [25]:
df.reset_index(inplace=True)

In [26]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0             77     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [27]:
df["salary"]*12

0    770400.0
1    584400.0
2    546000.0
3    871200.0
4    966000.0
5    679200.0
6    508800.0
7    812400.0
Name: salary, dtype: float64

In [28]:
df["salary"]*df["working_years"]

0    4943400.0
1      97400.0
2     136500.0
3     580800.0
4     563500.0
5     169800.0
6      84800.0
7     338500.0
dtype: float64

In [29]:
df["salary"].apply(np.sqrt)

0    253.377189
1    220.680765
2    213.307290
3    269.443872
4    283.725219
5    237.907545
6    205.912603
7    260.192237
Name: salary, dtype: float64

In [30]:
df["salary"].apply(lambda x: "high" if x>50000 else "low")

0    high
1     low
2     low
3    high
4    high
5    high
6     low
7    high
Name: salary, dtype: object

In [31]:
df["country"] = "Thailand"

In [32]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0             77     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country  
0  Thailand  
1  Thailand  
2  Thailand  
3  Thailand  
4  Thailand  
5  Thailand  
6  Thailand  
7  Thailand

In [33]:
df["bonus"] = df["salary"]*df["working_years"]

In [34]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0             77     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country      bonus  
0  Thailand  4943400.0  
1  Thailand    97400.0  
2  Thailand   136500.0  
3  Thailand   580800.0  
4  Thailand   563500.0  
5  Thailand   169800.0  
6  Thailand    84800.0  
7  Thailand   338500.0

In [35]:
df.drop([0,1,2] , inplace=True)

In [36]:
df

eid     name  gender department  age   salary  working_years birth_place  \
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018    Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0  
7  Thailand  338500.0

In [37]:
df.drop(["country","bonus"], axis=1, inplace=True)

In [38]:
df

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [39]:
df.sort_values("salary")

eid     name  gender department  age   salary  working_years birth_place
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
7  E018    Harit    male     devops   32  67700.0              5     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [40]:
df.sort_values("salary", ascending=False)

eid     name  gender department  age   salary  working_years birth_place
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi

In [41]:
df.groupby("department").mean()

age   salary  working_years
department                              
devops      32.0  67700.0            5.0
marketing   38.0  76550.0            7.5
support     30.5  49500.0            2.5

In [42]:
df.groupby(["department","gender"]).mean()

age   salary  working_years
department gender                              
devops     male    32.0  67700.0            5.0
marketing  female  39.0  72600.0            8.0
           male    37.0  80500.0            7.0
support    female  35.0  56600.0            3.0
           male    26.0  42400.0            2.0

In [43]:
df.groupby("department").agg(["mean", "count"])

age         salary       working_years      
            mean count     mean count          mean count
department                                               
devops      32.0     1  67700.0     1           5.0     1
marketing   38.0     2  76550.0     2           7.5     2
support     30.5     2  49500.0     2           2.5     2

In [44]:
df.groupby("department").agg({"age":["min","max"], "salary":"mean"})

age       salary
           min max     mean
department                 
devops      32  32  67700.0
marketing   37  39  76550.0
support     26  35  49500.0

In [45]:
df.to_csv("employee.csv")

In [46]:
df.to_csv("employee.csv", index=False)

In [47]:
df.to_csv("employee.csv", index=False, encoding='utf-8-sig')



---



https://rathachai.creatier.pro/